### ISSUE TITLE
Known low severity security vulnerability

### ISSUE THREAD

**Issue by peteyak** [nsip/sif-hits#1]
| nsip/sif-hits
-- | --
Known low severity security vulnerability detected in org.springframework.data:spring-data-jpa < 1.11.20 defined in pom.xml.    pom.xml update suggested: org.springframework.data:spring-data-jpa ~> 1.11.20. | Known low severity security vulnerability detected in org.springframework.data:spring-data-jpa < 1.11.20 defined in pom.xml. | pom.xml update suggested: org.springframework.data:spring-data-jpa ~> 1.11.20.
Known low severity security vulnerability detected in org.springframework.data:spring-data-jpa < 1.11.20 defined in pom.xml.
pom.xml update suggested: org.springframework.data:spring-data-jpa ~> 1.11.20.

**Comment by peteyak** [comment]
@bencart same issue and severity as the other I guess

**Comment by peteyak** [comment]
https://github.com/nsip/sif-hits/network/alert/pom.xml/org.springframework.data:spring-data-jpa/open

**Comment by bencart** [comment]
Does not affect our project.
